export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FULL_NAME_REQUEST = "FULL_NAME_REQUEST";
export const FULL_NAME_SUCCESS = "FULL_NAME_SUCCESS";
export const FULL_NAME_FAILURE = "FULL_NAME_FAILURE";

export const PRIMARY_SCHEDULE_REQUEST = "PRIMARY_SCHEDULE_REQUEST";
export const PRIMARY_SCHEDULE_SUCCESS = "PRIMARY_SCHEDULE_SUCCESS";
export const PRIMARY_SCHEDULE_FAILURE = "PRIMARY_SCHEDULE_FAILURE";

export const SECONDARY_SCHEDULE_REQUEST = "SECONDARY_SCHEDULE_REQUEST";
export const SECONDARY_SCHEDULE_SUCCESS = "SECONDARY_SCHEDULE_SUCCESS";
export const SECONDARY_SCHEDULE_FAILURE = "SECONDARY_SCHEDULE_FAILURE";

export const SCHEDULE_UPDATE_ALIAS = "SCHEDULE_UPDATE_ALIAS";
export const SCHEDULE_ADD_CUSTOM = "SCHEDULE_ADD_CUSTOM";
