export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const DO_LOGOUT = "DO_LOGOUT";

export const FULL_NAME_REQUEST = "FULL_NAME_REQUEST";
export const FULL_NAME_SUCCESS = "FULL_NAME_SUCCESS";
export const FULL_NAME_FAILURE = "FULL_NAME_FAILURE";

export const SCHEDULE_REQUEST = "SCHEDULE_REQUEST";
export const SCHEDULE_SUCCESS = "SCHEDULE_SUCCESS";
export const SCHEDULE_FAILURE = "SCHEDULE_FAILURE";

export const SCHEDULE_UPDATE_ALIAS = "SCHEDULE_UPDATE_ALIAS";
export const SCHEDULE_ADD_CUSTOM = "SCHEDULE_ADD_CUSTOM";
export const SCHEDULE_DEL_OR_HIDE = "SCHEDULE_DEL_OR_HIDE";
export const SCHEDULE_REMOVE_HIDDEN_RULE = "SCHEDULE_REMOVE_HIDDEN_RULE";

export const SET_DORM_PASSWORD = "SET_DORM_PASSWORD";
export const SET_DO_NOT_REMIND = "SET_DO_NOT_REMIND";
export const SET_LAST_SELF_VERSION = "SET_LAST_SELF_VERSION";
export const SET_CALENDAR_CONFIG = "SET_CALENDAR_CONFIG";

export const ADD_NEWS_CACHE = "ADD_NEWS_CACHE";

export const SET_GRADUATE = "SET_GRADUATE";
export const SET_NEW_GPA = "SET_NEW_GPA";
export const SET_BX = "SET_BX";
export const ADD_REPORT_HIDDEN = "ADD_REPORT_HIDDEN";
export const REMOVE_REPORT_HIDDEN = "REMOVE_REPORT_HIDDEN";

export const SET_SCHEDULE_HEIGHT = "SET_SCHEDULE_HEIGHT";

export const SET_REMAINDER_SHIFT = "SET_REMAINDER_SHIFT";

export const HOLE_SET_TOKEN = "HOLE_SET_TOKEN";

export const SET_LAST_BROADCAST_ID = "SET_LAST_BROADCAST_ID";
