export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const DO_LOGOUT = "DO_LOGOUT";

export const ADD_NEWS_CACHE = "ADD_NEWS_CACHE";

export const SET_CALENDAR_CONFIG = "SET_CALENDAR_CONFIG";
export const ADD_REPORT_HIDDEN = "ADD_REPORT_HIDDEN";
export const REMOVE_REPORT_HIDDEN = "REMOVE_REPORT_HIDDEN";

export const SET_DORM_PASSWORD = "SET_DORM_PASSWORD";

export const SCHEDULE_REQUEST = "SCHEDULE_REQUEST";
export const SCHEDULE_SUCCESS = "SCHEDULE_SUCCESS";
export const SCHEDULE_FAILURE = "SCHEDULE_FAILURE";
export const SCHEDULE_UPDATE_ALIAS = "SCHEDULE_UPDATE_ALIAS";
export const SCHEDULE_ADD_CUSTOM = "SCHEDULE_ADD_CUSTOM";
export const SCHEDULE_DEL_OR_HIDE = "SCHEDULE_DEL_OR_HIDE";
export const SCHEDULE_REMOVE_HIDDEN_RULE = "SCHEDULE_REMOVE_HIDDEN_RULE";
export const SCHEDULE_UPDATE_LOCATION = "SCHEDULE_UPDATE_LOCATION";
export const SCHEDULE_CLEAR = "SCHEDULE_CLEAR";

export const SET_ACTIVE_LIB_BOOK_RECORD = "SET_ACTIVE_LIB_BOOK_RECORD";
