import type {InfoHelper} from "../index";
import type {ToolPolicy} from "./types";

const read = (category: string, description: string, extra: Partial<ToolPolicy> = {}): ToolPolicy =>
    ({category, description, effect: "read", impact: "routine", mode: "direct", ...extra});
const write = (category: string, description: string, extra: Partial<ToolPolicy> = {}): ToolPolicy =>
    ({category, description, effect: "write", impact: "confirm", mode: "direct", ...extra});
const native = (category: string, description: string, route: string, privateArgs: string[] = []): ToolPolicy =>
    write(category, description, {mode: "interactive", route, privateArgs});
const internal = (reason: string): ToolPolicy =>
    ({category: "internal", description: reason, reason, effect: "read", impact: "confirm", mode: "internal"});

/**
 * Reviewed business effects, NOT guesses based on method names or HTTP verbs.
 * The generator requires every public callable, including hooks, to be classified.
 * Wrappers remain subject to the same policy as their underlying operation.
 */
export const agentMetadata = {
    mocked: internal("Runtime account state"),
    graduate: internal("Runtime account state"),
    clearCookieHandler: internal("Cookie infrastructure"),
    loginErrorHook: internal("Authentication hook"),
    twoFactorMethodHook: internal("Authentication hook"),
    twoFactorAuthHook: internal("Authentication hook"),
    twoFactorAuthLimitHook: internal("Authentication hook"),
    trustFingerprintHook: internal("Authentication hook"),
    trustFingerprintNameHook: internal("Authentication hook"),
    login: internal("Use the application's login UI"),
    logout: internal("Use account settings"),
    forgetDevice: native("account", "Forget this trusted device", "Account"),
    appStartUp: internal("App lifecycle and telemetry"),
    appUsageStat: internal("App telemetry"),
    getMadModelToken: internal("Model credential; never expose to the agent"),
    getLatestAnnounces: read("app", "Read THUInfo announcements"),
    getLatestVersion: read("app", "Check the latest THUInfo version"),
    submitFeedback: write("app", "Submit feedback to THUInfo maintainers"),
    getFeedbackReplies: read("app", "Read replies to submitted feedback"),
    getWeChatGroupQRCodeContent: read("app", "Get the THUInfo community QR code"),
    getPrivacyUrl: read("app", "Get the privacy policy link"),
    switchLang: write("account", "Change campus portal language"),
    getUserInfo: read("account", "Read the current student's profile"),
    naiveSendMail: write("app", "Send an email; confirm recipient, subject and full body"),
    getReport: read("academics", "Read course grades", {lock: "report"}),
    getAssessmentList: read("academics", "List teaching assessments"),
    getAssessmentForm: read("academics", "Read an assessment form", {mode: "wrapper"}),
    postAssessmentForm: native("academics", "Complete and submit a teaching assessment in the native screen", "Evaluation", ["form"]),
    getPhysicalExamResult: read("health", "Read physical examination results", {lock: "physicalExam"}),
    getClassroomList: read("academics", "List campus classrooms"),
    getClassroomState: read("academics", "Find classroom availability"),
    getInvoiceList: read("finance", "List invoices", {lock: "finance"}),
    getInvoicePDF: read("finance", "Open an invoice PDF", {lock: "finance", result: "document"}),
    getBankPayment: read("finance", "Read bank payments and grants", {lock: "finance"}),
    getGraduateIncome: read("finance", "Read graduate income", {lock: "finance"}),
    getCalendar: read("schedule", "Read the school calendar"),
    getCalendarYear: read("schedule", "Get the school calendar year"),
    getCalendarImageUrl: read("schedule", "Get the school calendar image link", {result: "document"}),
    getCountdown: read("schedule", "Read campus event countdowns"),
    getDormScore: read("dorm", "Open dormitory score image", {result: "document"}),
    // Despite its name this creates an order, so it must never run as a read.
    getEleRechargePayCode: native("dorm", "Create an electricity recharge order and pay in the native screen", "Electricity"),
    getElePayRecord: read("dorm", "Read electricity payment records", {lock: "finance"}),
    getEleRemainder: read("dorm", "Read remaining dormitory electricity"),
    resetDormPassword: native("account", "Change dormitory account password", "ResetDormPassword", ["newPassword"]),
    getLibraryList: read("library", "List libraries"),
    getLibrarySectionList: read("library", "List library sections for a floor and day"),
    getLibraryFloorList: read("library", "List library floors for a library and day"),
    getLibrarySeatList: read("library", "List seats and their availability"),
    toggleSocketState: write("library", "Switch a library seat power socket"),
    bookLibrarySeat: write("library", "Reserve a library seat", {mode: "wrapper"}),
    getBookingRecords: read("library", "Read library seat bookings"),
    cancelBooking: write("library", "Cancel a library seat booking. Pass the cancellable record's delId as id, not its display id", {mode: "wrapper"}),
    getLibraryRoomBookingCaptchaUrl: internal("Deprecated captcha API"),
    getLibraryRoomAccNo: internal("Library authentication identifier"),
    loginLibraryRoomBooking: internal("Wrapper-owned library authentication"),
    getLibraryRoomBookingInfoList: read("library", "List bookable library room types"),
    getLibraryRoomBookingResourceList: read("library", "List library room availability"),
    fuzzySearchLibraryId: read("library", "Look up a room booking member by exact name"),
    bookLibraryRoom: write("library", "Reserve a library room. The wrapper includes the current user automatically; additional members must come from fuzzySearchLibraryId", {mode: "wrapper"}),
    getLibraryRoomBookingRecord: read("library", "Read library room bookings"),
    cancelLibraryRoomBooking: write("library", "Cancel a library room booking", {mode: "wrapper"}),
    updateLibraryRoomEmail: write("library", "Change the library room booking email"),
    getNewsList: read("news", "List campus news by source"),
    searchNewsList: read("news", "Search campus news using keywords"),
    getNewsSubscriptionList: read("news", "List news subscriptions"),
    getNewsSourceList: read("news", "List news sources"),
    getNewsChannelList: read("news", "List news channels"),
    addNewsSubscription: write("news", "Add a requested news subscription", {impact: "routine"}),
    removeNewsSubscription: write("news", "Remove one requested news subscription", {impact: "routine"}),
    getNewsListBySubscription: read("news", "Read news for a subscription"),
    getNewsDetail: read("news", "Read a news article and cite its source URL", {mode: "wrapper", result: "news"}),
    addNewsToFavor: write("news", "Favorite a requested news article", {impact: "routine"}),
    removeNewsFromFavor: write("news", "Remove one requested news favorite", {impact: "routine"}),
    getFavorNewsList: read("news", "List favorite news articles"),
    getSchedule: read("schedule", "Read the campus schedule", {result: "schedule"}),
    saveCustomSchedule: write("schedule", "Synchronize selected local schedules to the portal", {mode: "wrapper"}),
    deleteCustomSchedule: write("schedule", "Delete selected custom schedules from the portal", {mode: "wrapper"}),
    getCrTimetable: read("courses", "Read course registration timetable"),
    getCrCaptchaUrl: internal("Native course registration authentication"),
    loginCr: internal("Native course registration authentication"),
    getCrAvailableSemesters: read("courses", "List available registration semesters"),
    getCrCoursePlan: read("courses", "Read the course plan for a semester"),
    searchCrRemaining: read("courses", "Search courses with remaining places"),
    searchCrPrimaryOpen: read("courses", "Search open primary courses"),
    searchCrCourses: read("courses", "Search course registration offerings"),
    selectCourse: write("courses", "Select a course; review semester, course, section and priority", {mode: "wrapper"}),
    deleteCourse: write("courses", "Drop a selected course", {mode: "wrapper"}),
    getSelectedCourses: read("courses", "Read selected courses for a semester"),
    changeCourseWill: write("courses", "Change course selection preference", {mode: "wrapper"}),
    getCrCurrentStage: read("courses", "Read the course registration stage"),
    searchCoursePriorityMeta: read("courses", "Read course priority metadata"),
    searchCoursePriorityInformation: read("courses", "Read course priority details"),
    getQueueInfo: read("courses", "Read course registration queue information"),
    cancelCoursePF: write("courses", "Cancel a course pass/fail request", {mode: "wrapper"}),
    setCoursePF: write("courses", "Request pass/fail grading for a course", {mode: "wrapper"}),
    getSportsResources: read("sports", "Find available sports resources"),
    updateSportsPhoneNumber: write("sports", "Change sports reservation phone number"),
    getSportsCaptchaUrl: internal("Native reservation captcha"),
    makeSportsReservation: native("sports", "Reserve a sports facility with native captcha and payment", "Sports", ["captcha"]),
    getSportsReservationRecords: read("sports", "Read sports reservations"),
    paySportsReservation: native("sports", "Pay for a sports reservation", "SportsRecord"),
    unsubscribeSportsReservation: write("sports", "Cancel an unpaid sports reservation", {mode: "wrapper"}),
    getGitNamespaces: read("gitlab", "List GitLab namespaces"),
    getGitRecentProjects: read("gitlab", "List recent GitLab projects"),
    getGitOwnedProjects: read("gitlab", "List owned GitLab projects"),
    searchGitProjects: read("gitlab", "Search GitLab projects"),
    getGitStarredProjects: read("gitlab", "List starred GitLab projects"),
    getGitProjectDetail: read("gitlab", "Read GitLab project details"),
    getGitProjectTree: read("gitlab", "List files in a GitLab project"),
    getGitProjectBranches: read("gitlab", "List project branches"),
    getGitProjectFileBlob: read("gitlab", "Read a bounded project file"),
    renderGitMarkdown: internal("Presentation helper; use native Markdown rendering"),
    searchReservesLib: read("library", "Search course reserve books"),
    getReservesLibBookDetail: read("library", "Read course reserve book details"),
    reservesLibDownloadChapters: native("library", "Download reserve book chapters in the native library screen", "ReservesLibWelcome", ["setCompletion"]),
    getDegreeProgramCompletion: read("academics", "Read degree program completion", {lock: "report"}),
    getFullDegreeProgram: read("academics", "Read the degree program requirements"),
    getNetworkVerificationImageUrl: internal("Native network login captcha"),
    loginUsereg: internal("Native network login"),
    getOnlineDevices: read("network", "List online network devices"),
    getNetworkBalance: read("network", "Read network balance"),
    getNetworkAccountInfo: read("network", "Read network account usage"),
    logoutNetworkDevice: write("network", "Disconnect a network device", {mode: "wrapper"}),
    loginNetworkDevice: native("network", "Connect a network device", "NetworkLogin"),
    getScoreByCourseId: read("thos", "Read a THOS course score", {lock: "report"}),
    prepareThosSession: internal("Wrapper-owned THOS authentication"),
    getThosTasks: read("thos", "Read THOS workflow tasks"),
    getThosServices: read("thos", "List THOS services"),
    loginCampusCard: internal("Native campus card authentication"),
    getCampusCardInfo: read("card", "Read campus card balance and status", {lock: "finance"}),
    getCampusCardPhotoUrl: read("card", "Open campus card photo", {result: "document"}),
    getCampusCardTransactions: read("card", "Read campus card transactions", {lock: "finance"}),
    changeCampusCardPassword: native("card", "Change campus card password", "ECard", ["oldPassword", "newPassword"]),
    modifyCampusCardMaxTransactionAmount: native("card", "Change campus card spending limits", "ECard", ["transactionPassword"]),
    reportCampusCardLoss: native("card", "Report campus card lost", "ECard", ["transactionPassword"]),
    cancelCampusCardLoss: native("card", "Cancel campus card loss report", "ECard", ["transactionPassword"]),
    rechargeCampusCard: native("card", "Recharge the campus card", "ECard", ["transactionPassword"]),
} satisfies Partial<Record<keyof InfoHelper, ToolPolicy>>;
