name: Build Android and iOS

on: push

jobs:
  build-harmony:
    runs-on: ubuntu-latest
    container: ghcr.io/sanchuanhehe/harmony-next-pipeline-docker/harmonyos-ci-image:v5.0.4
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup caching
        if: startsWith(github.ref, 'refs/tags') == false
        uses: actions/cache@v4
        with:
          path: |
            apps/thu-info-app/node_modules
          key: cache-harmony-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            cache-harmony-
      - name: Setup Harmony
        run: |
          npm install -g yarn
          ./setup-harmony.sh
      - name: Install dependencies
        working-directory: apps/thu-info-app/harmony
        run: |
          ohpm install --all
      - name: Bundle project
        working-directory: apps/thu-info-app
        run: |
          yarn codegen-harmony
          yarn bundle-harmony
      - name: Build project
        working-directory: apps/thu-info-app/harmony
        run: |
          hvigorw clean --no-daemon
          hvigorw assembleHap --mode module -p product=default -p buildMode=debug --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: harmony-output
          path: apps/thu-info-app/harmony/entry/build/default/outputs/default
