name: Test and Publish

on: push

permissions:
  id-token: write
  contents: read

jobs:
  unit-test-and-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup caching
        uses: actions/cache@v5
        with:
          path: |
            node_modules
            */*/node_modules
          key: cache-${{ runner.OS }}-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            cache-${{ runner.OS }}-
      - name: Install dependencies
        run: |
          yarn
      - name: Run tests
        env:
          INFO_USER_ID: ${{ secrets.INFO_USER_ID }}
          INFO_PASSWORD: ${{ secrets.INFO_PASSWORD }}
        run: |
          yarn workspace @thu-info/lib lint
        #  yarn workspace @thu-info/lib test
      - name: Build demo
        run: |
          yarn workspace @thu-info/lib build-dist
      - name: Upload demo
        uses: actions/upload-artifact@v7
        with:
          name: demo
          path: ./packages/thu-info-lib/demo/
